name: ROS

on:
  push:
    branches: [foxy]
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest
    container: athackst/ros2:foxy-dev
    steps:
      - uses: actions/checkout@v2
      - name: "Get workspace"
        run: |
          if [ -f ros2.repos ]; then
            vcs import --skip-existing < ros2.repos src
          fi
      - name: "Get dependencies"
        run: |
          sudo apt-get update
          rosdep update
          rosdep install --from-paths src --ignore-src -y --rosdistro=foxy
          sudo apt-get install ros-foxy-dynamixel-sdk


      - name: "Build"
        run: |
          colcon build --cmake-args '-DCMAKE_BUILD_TYPE=RelWithDebInfo' -Wall -Wextra -Wpedantic
        continue-on-error: true
      - name: "Test"
        run: |
          colcon test
  lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    container: athackst/ros2:foxy-dev
    strategy:
      fail-fast: false
      matrix:
          linter: [cppcheck, cpplint, lint_cmake, pep257]
    steps:
      - uses: actions/checkout@v2
      - name: "Get workspace"
        run: |
          if [ -f ros2.repos ]; then
            vcs import --skip-existing < ros2.repos src
          fi
      - name: "run linter"
        run: |
          ament_${{ matrix.linter }} src/
